# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBLOGAccess():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_bLOGAccess(self):
    # Test name: BLOG Access
    # Step # | name | target | value | comment
    # 1 | open | https://www.guildeducation.com/ |  | Open Homepage
    self.driver.get("https://www.guildeducation.com/")
    # 2 | setWindowSize | 1024x768 |  | Set a Standard Window Size for Browser
    self.driver.set_window_size(1024, 768)
    # 3 | verifyElementPresent | css=h1 |  | Verify Homepage Element css=h1
    elements = self.driver.find_elements(By.CSS_SELECTOR, "h1")
    assert len(elements) > 0
    # 4 | click | id=menu-item-652 |  | Click For Employers Menu Item
    self.driver.find_element(By.ID, "menu-item-652").click()
    # 5 | verifyElementPresent | css=#menu-item-652 > .sub-menu |  | Verify Element For Employers Sub-Menu
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#menu-item-652 > .sub-menu")
    assert len(elements) > 0
    # 6 | click | css=#menu-item-1354 > a > span |  | Click For Learning Providers Menu Item
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-1354 > a > span").click()
    # 7 | verifyElementPresent | css=#menu-item-1354 > .sub-menu |  | Verify Element For Learning Providers Sub-Menu
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#menu-item-1354 > .sub-menu")
    assert len(elements) > 0
    # 8 | click | css=#menu-item-2394 > a > span |  | Click Resources Menu Item
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-2394 > a > span").click()
    # 9 | verifyElementPresent | css=#menu-item-2394 > .sub-menu |  | Verify Element Resources Sub-Menu
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#menu-item-2394 > .sub-menu")
    assert len(elements) > 0
    # 10 | click | css=#menu-item-653 > a > span |  | Click About Us Menu Item
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-653 > a > span").click()
    # 11 | verifyElementPresent | css=#menu-item-653 > .sub-menu |  | About Us Verification
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#menu-item-653 > .sub-menu")
    assert len(elements) > 0
    # 12 | click | linkText=FAQs |  | Click LinkText=FAQs from About Us Menu Item
    self.driver.find_element(By.LINK_TEXT, "FAQs").click()
    # 13 | click | id=menu-item-653 |  | Click About Us from Menu
    self.driver.find_element(By.ID, "menu-item-653").click()
    # 14 | click | css=#menu-item-2394 > a > span |  | Click Resoures Menu-Item
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-2394 > a > span").click()
    # 15 | click | css=#menu-item-2395 span |  | Click BLOG Link
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-2395 span").click()
    # 16 | verifyElementPresent | css=.hp-top-post |  | Verify Element Top-Post CSS Window
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".hp-top-post")
    assert len(elements) > 0
  
